#!/bin/bash
BAR_FONT='-*-gohufont-medium-r-*-*-11-*-*-*-*-*-iso8859-*'
BAR_BACKGROUND='\#ff0a0a0a'

bash -c "bar.content.sh 2> /dev/null |  lemonbar -d -p -f ${BAR_FONT}  -B ${BAR_BACKGROUND} & disown"

exit
